// List of drinks and mixers
export const drinks_options = [
  "Absinthe",
  "Amaretto",
  "Applejack",
  "Baileys",
  "Benedictine",
  "Blue Curacao",
  "Brandy",
  "Campari",
  "Champagne",
  "Cherry Liqueur",
  "Cognac",
  "Cointreau",
  "Cola",
  "Cranberry Juice",
  "Drambuie",
  "Egg Whites",
  "Espresso",
  "Galliano",
  "Ginger Beer",
  "Gin",
  "Grand Marnier",
  "Grapefruit Soda",
  "Grenadine",
  "Jack Daniel's",
  "Kahlua",
  "Lemon Juice",
  "Lemonade",
  "Lime Juice",
  "Liqueur",
  "Mint Leaves Syrup",
  "Orange Juice",
  "Passion Fruit Juice",
  "Peach Puree",
  "Peach Schnapps",
  "Pineapple Juice",
  "Pisco",
  "Prosecco",
  "Raspberry Syrup",
  "Rum",
  "Sambuca",
  "Scotch",
  "Simple Syrup",
  "Soda Water",
  "Sugar Syrup",
  "Tequila",
  "Tomato Juice",
  "Tonic Water",
  "Triple Sec",
  "Vermouth",
  "Vodka",
  "Whiskey"
];


// Dictionary mapping drinks and mixers to image files
export const image_paths = {
  "Rum": require('./images/rum.png'),
  "Vodka": require('./images/vodka.png'),
  "Tequila": require('./images/tequila.png'),
  "Whiskey": require('./images/whiskey.png'),
  "Gin": require('./images/gin.png'),
  "Brandy": require('./images/brandy.png'),
  "Triple Sec": require('./images/triple_sec.png'),
  "Vermouth": require('./images/vermouth.png'),
  "Cointreau": require('./images/cointreau.png'),
  "Campari": require('./images/campari.png'),
  "Amaretto": require('./images/amaretto.png'),
  "Kahlua": require('./images/kahlua.png'),
  "Baileys": require('./images/baileys.png'),
  "Absinthe": require('./images/absinthe.png'),
  "Sambuca": require('./images/sambuca.png'),
  "Liqueur": require('./images/liqueur.png'),
  "Cognac": require('./images/cognac.png'),
  "Grand Marnier": require('./images/grand_marnier.png'),
  "Prosecco": require('./images/prosecco.png'),
  "Champagne": require('./images/champagne.png'),
  "Scotch": require('./images/scotch.png'),
  "Applejack": require('./images/applejack.png'),
  "Jack Daniel's": require('./images/jack_daniels.png'),
  "Pisco": require('./images/pisco.png'),
  "Galliano": require('./images/galliano.png'),
  "Blue Curacao": require('./images/blue_curacao.png'),
  "Benedictine": require('./images/benedictine.png'),
  "Drambuie": require('./images/drambuie.png'),
  "Peach Schnapps": require('./images/peach_schnapps.png'),
  "Cherry Liqueur": require('./images/cherry_liqueur.png'),
  "Lemon Juice": require('./images/lemon_juice.png'),
  "Lime Juice": require('./images/lime_juice.png'),
  "Orange Juice": require('./images/orange_juice.png'),
  "Cranberry Juice": require('./images/cranberry_juice.png'),
  "Pineapple Juice": require('./images/pineapple_juice.png'),
  "Simple Syrup": require('./images/simple_syrup.png'),
  "Grenadine": require('./images/grenadine.png'),
  "Tonic Water": require('./images/tonic_water.png'),
  "Soda Water": require('./images/soda_water.png'),
  "Ginger Beer": require('./images/ginger_beer.png'),
  "Cola": require('./images/cola.png'),
  // "Bitters": require('./images/bitters.png'),
  "Espresso": require('./images/espresso.png'),
  "Grapefruit Soda": require('./images/grapefruit_soda.png'),
  "Passion Fruit Juice": require('./images/passion_fruit_juice.png'),
  "Raspberry Syrup": require('./images/raspberry_syrup.png'),
  "Lemonade": require('./images/lemonade.png'),
  "Peach Puree": require('./images/peach_puree.png'),
  "default": require('./images/drink.png'),
};

// Dictionary of cocktails and their ingredients
export const cocktails = {
  "Margarita": { "Tequila": 50, "Triple Sec": 25, "Lime Juice": 25 },
  "Martini": { "Gin": 60, "Vermouth": 10 },
  "Mojito": { "Rum": 50, "Lime Juice": 20, "Simple Syrup": 20, "Soda Water": 50 },
  "Cosmopolitan": { "Vodka": 40, "Triple Sec": 15, "Cranberry Juice": 30, "Lime Juice": 15 },
  "Old Fashioned": { "Whiskey": 60, "Bitters": 2, "Sugar Syrup": 10 },
  "Pina Colada": { "Rum": 50, "Pineapple Juice": 90, "Coconut Cream": 60 },
  "Whiskey Sour": { "Whiskey": 60, "Lemon Juice": 30, "Simple Syrup": 20 },
  "Daiquiri": { "Rum": 60, "Lime Juice": 20, "Simple Syrup": 20 },
  "Bloody Mary": { "Vodka": 50, "Tomato Juice": 100, "Lemon Juice": 25 },
  "Tom Collins": { "Gin": 60, "Lemon Juice": 30, "Simple Syrup": 20, "Soda Water": 60 },
  "Black Russian": { "Vodka": 50, "Kahlua": 25 },
  "White Russian": { "Vodka": 50, "Kahlua": 25, "Cream": 25 },
  "Mai Tai": { "Rum": 40, "Triple Sec": 15, "Lime Juice": 15, "Amaretto": 15 },
  "Negroni": { "Gin": 30, "Campari": 30, "Vermouth": 30 },
  "Manhattan": { "Whiskey": 60, "Vermouth": 30, "Bitters": 2 },
  "Sidecar": { "Cognac": 50, "Triple Sec": 20, "Lemon Juice": 20 },
  "French 75": { "Gin": 30, "Lemon Juice": 15, "Simple Syrup": 15, "Champagne": 90 },
  "Bellini": { "Prosecco": 90, "Peach Puree": 30 },
  "Mimosa": { "Champagne": 90, "Orange Juice": 90 },
  "Aperol Spritz": { "Aperol": 60, "Prosecco": 90, "Soda Water": 30 },
  "Sazerac": { "Cognac": 60, "Absinthe": 5, "Sugar Syrup": 10, "Bitters": 2 },
  "Caipirinha": { "Cachaça": 60, "Lime Juice": 25, "Sugar Syrup": 15 },
  "Gimlet": { "Gin": 60, "Lime Juice": 15, "Simple Syrup": 15 },
  "Vesper": { "Gin": 60, "Vodka": 15, "Lillet Blanc": 10 },
  "Rusty Nail": { "Scotch": 45, "Drambuie": 25 },
  "B-52": { "Kahlua": 20, "Baileys": 20, "Grand Marnier": 20 },
  "Tequila Sunrise": { "Tequila": 50, "Orange Juice": 100, "Grenadine": 10 },
  "Espresso Martini": { "Vodka": 50, "Kahlua": 25, "Espresso": 25 },
  "Moscow Mule": { "Vodka": 60, "Lime Juice": 10, "Ginger Beer": 90 },
  "Mint Julep": { "Bourbon": 60, "Mint Leaves Syrup": 10, "Simple Syrup": 20 },
  "Brandy Alexander": { "Brandy": 40, "Dark Creme de Cacao": 25, "Cream": 25 },
  "Clover Club": { "Gin": 45, "Raspberry Syrup": 15, "Lemon Juice": 20, "Egg White": 10 },
  "Paloma": { "Tequila": 50, "Lime Juice": 10, "Grapefruit Soda": 140 },
  "Planter's Punch": {
    "Dark Rum": 45, "Orange Juice": 35, "Pineapple Juice": 35, "Lime Juice": 10, "Grenadine": 10,
  },
  "Sea Breeze": { "Vodka": 50, "Cranberry Juice": 100, "Grapefruit Juice": 50 },
  "Sex on the Beach": {
    "Vodka": 40, "Peach Schnapps": 20, "Cranberry Juice": 40, "Orange Juice": 40,
  },
  "Blue Lagoon": { "Vodka": 40, "Blue Curacao": 30, "Lemonade": 100 },
  "Godfather": { "Scotch": 50, "Amaretto": 25 },
  "Harvey Wallbanger": { "Vodka": 45, "Galliano": 15, "Orange Juice": 90 },
  "Jack Rose": { "Applejack": 45, "Lemon Juice": 15, "Grenadine": 15 },
  "Kamikaze": { "Vodka": 30, "Triple Sec": 30, "Lime Juice": 30 },
  "Lynchburg Lemonade": {
    "Jack Daniel's": 45, "Triple Sec": 15, "Lemon Juice": 30, "Lemonade": 90,
  },
  "Painkiller": {
    "Pusser's Rum": 60, "Pineapple Juice": 90, "Orange Juice": 30, "Coconut Cream": 30,
  },
  "Pisco Sour": { "Pisco": 60, "Lime Juice": 30, "Simple Syrup": 20, "Egg White": 10 },
  "Rum Punch": {
    "Rum": 45, "Pineapple Juice": 60, "Orange Juice": 60, "Grenadine": 15,
  },
};
